export const searchData = [
  // Courses
  { name: "AI", category: "Courses" },
  { name: "Data Science", category: "Courses" },
  { name: "React.js, Next.js, Tailwind CSS, TypeScript", category: "Courses" },
  { name: "ChatGPT", category: "Courses" },
  { name: "Generative AI", category: "Courses" },
  { name: "Data Analysis", category: "Courses" },
  { name: "Programming Languages", category: "Courses" },
  { name: "Cloud Computing", category: "Courses" },
  { name: "Web Development", category: "Courses" },
  { name: "AWS (Amazon Web Services)", category: "Courses" },
  { name: "DevOps", category: "Courses" },
  { name: "UI/UX Design", category: "Courses" },
  { name: "Cybersecurity", category: "Courses" },
  { name: "Big Data", category: "Courses" },
  { name: "Software Development", category: "Courses" },
  { name: "Data Structures and Algorithms (DSA)", category: "Courses" },
  { name: "Python", category: "Courses" },
  { name: "C++", category: "Courses" },
  { name: "Java", category: "Courses" },
  { name: "R", category: "Courses" },
  { name: "Ruby", category: "Courses" },

  // Cheatsheets
  { name: "HTML Cheat Sheet", category: "Cheatsheets" },
  { name: "CSS Cheat Sheet", category: "Cheatsheets" },
  { name: "JavaScript Cheat Sheet", category: "Cheatsheets" },
  { name: "React.js Cheat Sheet", category: "Cheatsheets" },
  { name: "Node.js Cheat Sheet", category: "Cheatsheets" },
  { name: "Tailwind CSS Cheat Sheet", category: "Cheatsheets" },
  { name: "Next.js Cheat Sheet", category: "Cheatsheets" },
  { name: "Python Cheat Sheet", category: "Cheatsheets" },
  { name: "Java Cheat Sheet", category: "Cheatsheets" },
  { name: "PHP Cheat Sheet", category: "Cheatsheets" },
  { name: "Ruby Cheat Sheet", category: "Cheatsheets" },
  { name: "User Authentication Cheat Sheet", category: "Cheatsheets" },
  { name: "Security Practices Cheat Sheet", category: "Cheatsheets" },
  { name: "Docker Cheat Sheet", category: "Cheatsheets" },
  { name: "CI/CD Cheat Sheet", category: "Cheatsheets" },
  { name: "Cloud Deployment Cheat Sheet", category: "Cheatsheets" },
  { name: "System Design Cheat Sheet", category: "Cheatsheets" },
  { name: "Performance Optimization Cheat Sheet", category: "Cheatsheets" },
  { name: "Cyber Security Cheat Sheet", category: "Cheatsheets" },
  { name: "Blockchain Cheat Sheet", category: "Cheatsheets" },
  { name: "NoSQL Cheat Sheet", category: "Cheatsheets" },
  { name: "MongoDB Cheat Sheet", category: "Cheatsheets" },

  // DSA and Aptitude
  { name: "DSA Roadmap", category: "DSAandAptitude" },
  { name: "DSA Problems Sheet - Love Babbar", category: "DSAandAptitude" },
  { name: "DSA Problems Sheet - Nishanth Chahar", category: "DSAandAptitude" },
  { name: "DSA Problems Sheet - Shraddha Khapra", category: "DSAandAptitude" },
  { name: "DSA in JAVA", category: "DSAandAptitude" },
  { name: "DSA in C++", category: "DSAandAptitude" },
  { name: "Qualitative Aptitude", category: "DSAandAptitude" },
  { name: "Quantitative Aptitude", category: "DSAandAptitude" }
];

localStorage.setItem(
  "searchData",
  JSON.stringify([
    { name: "DSA Roadmap", category: "DSAandAptitude" },
    { name: "DSA Problems Sheet - Nishanth Chahar", category: "DSAandAptitude" },
  { name: "DSA Problems Sheet - Shraddha Khapra", category: "DSAandAptitude" },
  { name: "DSA in JAVA", category: "DSAandAptitude" },
  { name: "DSA in C++", category: "DSAandAptitude" },
  { name: "Qualitative Aptitude", category: "DSAandAptitude" },
  { name: "Quantitative Aptitude", category: "DSAandAptitude" },
    { name: "DSA sheet by Love Babbar", category: "DSAandAptitude" },
    { name: "HTML Cheat Sheet", category: "Cheatsheets" },
  { name: "CSS Cheat Sheet", category: "Cheatsheets" },
  { name: "JavaScript Cheat Sheet", category: "Cheatsheets" },
  { name: "React.js Cheat Sheet", category: "Cheatsheets" },
  { name: "Node.js Cheat Sheet", category: "Cheatsheets" },
  { name: "Tailwind CSS Cheat Sheet", category: "Cheatsheets" },
  { name: "Next.js Cheat Sheet", category: "Cheatsheets" },
  { name: "Python Cheat Sheet", category: "Cheatsheets" },
  { name: "Java Cheat Sheet", category: "Cheatsheets" },
  { name: "PHP Cheat Sheet", category: "Cheatsheets" },
  { name: "Ruby Cheat Sheet", category: "Cheatsheets" },
  { name: "User Authentication Cheat Sheet", category: "Cheatsheets" },
  { name: "Security Practices Cheat Sheet", category: "Cheatsheets" },
  { name: "Docker Cheat Sheet", category: "Cheatsheets" },
  { name: "CI/CD Cheat Sheet", category: "Cheatsheets" },
  { name: "Cloud Deployment Cheat Sheet", category: "Cheatsheets" },
  { name: "System Design Cheat Sheet", category: "Cheatsheets" },
  { name: "Performance Optimization Cheat Sheet", category: "Cheatsheets" },
  { name: "Cyber Security Cheat Sheet", category: "Cheatsheets" },
  { name: "Blockchain Cheat Sheet", category: "Cheatsheets" },
  { name: "NoSQL Cheat Sheet", category: "Cheatsheets" },
  { name: "MongoDB Cheat Sheet", category: "Cheatsheets" },
  { name: "AI", category: "Courses" },
  { name: "Data Science", category: "Courses" },
  { name: "React.js, Next.js, Tailwind CSS, TypeScript", category: "Courses" },
  { name: "ChatGPT", category: "Courses" },
  { name: "Generative AI", category: "Courses" },
  { name: "Data Analysis", category: "Courses" },
  { name: "Programming Languages", category: "Courses" },
  { name: "Cloud Computing", category: "Courses" },
  { name: "Web Development", category: "Courses" },
  { name: "AWS (Amazon Web Services)", category: "Courses" },
  { name: "DevOps", category: "Courses" },
  { name: "UI/UX Design", category: "Courses" },
  { name: "Cybersecurity", category: "Courses" },
  { name: "Big Data", category: "Courses" },
  { name: "Software Development", category: "Courses" },
  { name: "Data Structures and Algorithms (DSA)", category: "Courses" },
  { name: "Python", category: "Courses" },
  { name: "C++", category: "Courses" },
  { name: "Java", category: "Courses" },
  { name: "R", category: "Courses" },
  { name: "Ruby", category: "Courses" },
    // Add more items as needed
  ])
);
